project:
  type: website
  output-dir: "docs"

website:
  title: "CGBeta"
  favicon: "images/beta_small_logo.png"
  navbar:
    logo: "images/BTEAM_logo.png"
    title: false
    left:
      - href: index.qmd
        text: "HOME"
      - text: "기술문서"
        menu:
          - href: overview.qmd
            text: "개발개요"
          - text: "-----------"
          - href: data.qmd
            text: "데이터"

    right:
      - about.qmd

    tools:
      - icon: github
        href: https://github.com/aivocado/cgbside

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css